const express=require('express')
const router =express.Router()
const user_handler=require('../router_handler/user')
const express_joi=require('@escook/express-joi')
const{reg_schema, login_schema}=require('../schema/user')
router.post('/reguser',express_joi(reg_schema),user_handler.regUser)
router.post('/login',express_joi(login_schema),user_handler.login)
router.get('/article_list',user_handler.get_article_list)
router.get('/article',user_handler.get_article)
router.get('/n_best_article',user_handler.get_n_best_article)
router.get('/n_newest_article',user_handler.get_n_newest_article)
router.get('/visit_time_today',user_handler.get_visit_time_today)
router.get('/visit_ip_today',user_handler.get_visit_ip_today)
router.get('/visit_time_list',user_handler.get_visit_time_list)
router.get('/visit_ip_list',user_handler.get_visit_ip_list)
router.get('/visit_time_list_all',user_handler.get_visit_time_list_all)
router.get('/visit_ip_list_all',user_handler.get_visit_ip_list_all)
router.get('/comment_list',user_handler.get_comment_list)
router.get('/thumbs_up_num',user_handler.get_thumbs_up_num)
router.get('/read_time_list',user_handler.get_read_time_list)
router.get('/read_ip_list',user_handler.get_read_ip_list)
router.get('/index_show',user_handler.get_index_show_list)
router.get('/article_main_info',user_handler.get_article_main_info)
router.get('/webgl_list',user_handler.get_webgl_list)
module.exports=router